// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

#include "index.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace playground {

inline constexpr PositionHashIndex::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        account_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contract_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR PositionHashIndex::PositionHashIndex(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PositionHashIndexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionHashIndexDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionHashIndexDefaultTypeInternal() {}
  union {
    PositionHashIndex _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionHashIndexDefaultTypeInternal _PositionHashIndex_default_instance_;
}  // namespace playground
static ::_pb::Metadata file_level_metadata_index_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_index_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_index_2eproto = nullptr;
const ::uint32_t TableStruct_index_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::playground::PositionHashIndex, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::playground::PositionHashIndex, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::playground::PositionHashIndex, _impl_.contract_id_),
    PROTOBUF_FIELD_OFFSET(::playground::PositionHashIndex, _impl_.account_id_),
    1,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::playground::PositionHashIndex)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::playground::_PositionHashIndex_default_instance_._instance,
};
const char descriptor_table_protodef_index_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013index.proto\022\nplayground\"<\n\021PositionHas"
    "hIndex\022\023\n\013contract_id\030\001 \001(\003\022\022\n\naccount_i"
    "d\030\002 \001(\t"
};
static ::absl::once_flag descriptor_table_index_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_index_2eproto = {
    false,
    false,
    87,
    descriptor_table_protodef_index_2eproto,
    "index.proto",
    &descriptor_table_index_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_index_2eproto::offsets,
    file_level_metadata_index_2eproto,
    file_level_enum_descriptors_index_2eproto,
    file_level_service_descriptors_index_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_index_2eproto_getter() {
  return &descriptor_table_index_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_index_2eproto(&descriptor_table_index_2eproto);
namespace playground {
// ===================================================================

class PositionHashIndex::_Internal {
 public:
  using HasBits = decltype(std::declval<PositionHashIndex>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_._has_bits_);
  static void set_has_contract_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_account_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

PositionHashIndex::PositionHashIndex(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:playground.PositionHashIndex)
}
inline PROTOBUF_NDEBUG_INLINE PositionHashIndex::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        account_id_(arena, from.account_id_) {}

PositionHashIndex::PositionHashIndex(
    ::google::protobuf::Arena* arena,
    const PositionHashIndex& from)
    : ::google::protobuf::Message(arena) {
  PositionHashIndex* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.contract_id_ = from._impl_.contract_id_;

  // @@protoc_insertion_point(copy_constructor:playground.PositionHashIndex)
}
inline PROTOBUF_NDEBUG_INLINE PositionHashIndex::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        account_id_(arena) {}

inline void PositionHashIndex::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.contract_id_ = {};
}
PositionHashIndex::~PositionHashIndex() {
  // @@protoc_insertion_point(destructor:playground.PositionHashIndex)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PositionHashIndex::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.account_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PositionHashIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:playground.PositionHashIndex)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.account_id_.ClearNonDefaultToEmpty();
  }
  _impl_.contract_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PositionHashIndex::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> PositionHashIndex::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PositionHashIndex_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string account_id = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_.account_id_)}},
    // optional int64 contract_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PositionHashIndex, _impl_.contract_id_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_.contract_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 contract_id = 1;
    {PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_.contract_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string account_id = 2;
    {PROTOBUF_FIELD_OFFSET(PositionHashIndex, _impl_.account_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\12\0\0\0\0\0"
    "playground.PositionHashIndex"
    "account_id"
  }},
};

::uint8_t* PositionHashIndex::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:playground.PositionHashIndex)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int64 contract_id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_contract_id(), target);
  }

  // optional string account_id = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_account_id();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "playground.PositionHashIndex.account_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:playground.PositionHashIndex)
  return target;
}

::size_t PositionHashIndex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:playground.PositionHashIndex)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string account_id = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_account_id());
    }

    // optional int64 contract_id = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_contract_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PositionHashIndex::_class_data_ = {
    PositionHashIndex::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PositionHashIndex::GetClassData() const {
  return &_class_data_;
}

void PositionHashIndex::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PositionHashIndex*>(&to_msg);
  auto& from = static_cast<const PositionHashIndex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:playground.PositionHashIndex)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_account_id(from._internal_account_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.contract_id_ = from._impl_.contract_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PositionHashIndex::CopyFrom(const PositionHashIndex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:playground.PositionHashIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PositionHashIndex::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PositionHashIndex::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PositionHashIndex::InternalSwap(PositionHashIndex* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_id_, &other->_impl_.account_id_, arena);
        swap(_impl_.contract_id_, other->_impl_.contract_id_);
}

::google::protobuf::Metadata PositionHashIndex::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_index_2eproto_getter, &descriptor_table_index_2eproto_once,
      file_level_metadata_index_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace playground
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
